### ISSUE TITLE
Error in log related to ClassLoading / CuriosHook not found

### ISSUE THREAD

**Issue by brisingraerowing** [RakambdaOrg/OverpoweredMending#119]
### Describe the bug

An error pops up in the game log related to class loading not finding the CuriosHook class.

### Minecraft version

1.18.2

### Forge version

40.1.73

### Mod version

2.4.2

### Relevant log output

```shell
[17:19:00] [modloading-worker-0/ERROR] [fr.ra.ov.fo.OverpoweredMending/]: Failed to hook into Curios
java.lang.ClassNotFoundException: fr.raksrinana.overpoweredmending.forge.hooks.CuriosHook
	at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?] {}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?] {}
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:134) ~[securejarhandler-1.0.3.jar:?] {}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?] {}
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:134) ~[securejarhandler-1.0.3.jar:?] {}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?] {}
	at java.lang.Class.forName0(Native Method) ~[?:?] {re:mixin}
	at java.lang.Class.forName(Class.java:375) ~[?:?] {re:mixin}
	at fr.raksrinana.overpoweredmending.forge.OverpoweredMending.initCurios(OverpoweredMending.java:32) ~[OverpoweredMending-1.18.2-2.4.2.jar%23378!/:2.4.2] {re:classloading}
	at fr.raksrinana.overpoweredmending.forge.OverpoweredMending.<init>(OverpoweredMending.java:23) ~[OverpoweredMending-1.18.2-2.4.2.jar%23378!/:2.4.2] {re:classloading}
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?] {}
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?] {}
	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:67) ~[javafmllanguage-1.18.2-40.1.73.jar%23510!/:?] {}
	at net.minecraftforge.client.loading.ClientModLoader.mdaa05cf$lambda$init$1$2(ClientModLoader.java:555) ~[forge-1.18.2-40.1.73-universal.jar%23513!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:better_loading_screen.mixins.json:MixinClientModLoader,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:106) ~[fmlcore-1.18.2-40.1.73.jar%23509!/:?] {re:mixin}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) [?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) [?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) [?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) [?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) [?:?] {re:mixin,re:computing_frames}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) [?:?] {re:mixin,re:computing_frames}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) [?:?] {re:mixin}
```

**Comment by Rakambda** [comment]
Can you try with this build and see if it fixes the error?
https://github.com/RakSrinaNa/OverpoweredMending/actions/runs/3195770040 (the mod is in a zip that you can download in the artifacts section)

**Comment by brisingraerowing** [comment]
The error no longer shows up, so I'd say that fixes it.
